#!/bin/bash
echo "Starting OpenVAS Services..."
/etc/init.d/./greenbone-security-assistant start
/etc/init.d/./openvas-scanner start
/etc/init.d/./openvas-administrator start
/etc/init.d/./openvas-manager start 

openvas-start